# Documentation: https://github.com/codecov/support/wiki/codecov.yml

coverage:
  precision: 3
  round: down
  range: 80...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: off
    patch:
      default:
        informational: true
    changes: off

comment: false
